version: "3"

services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_events
      MYSQL_USER: events_user
      MYSQL_PASSWORD: mysql